---
.travis.yml:
  secure: "Qvf6e0d8zyEQ2RkUFQB14wXE7dPS/+lN0WCgs79udjKp4UCRDvrIdDW6JROg5k1Kw75rQ+VuhyW2e3QXFfW65nlVrciipYlSYyA5iZaLV4ffy1NLhuscIMwuX6SNe22ut7oNB+kNfKX/rT3jnUfrg28UjJ3r4TYvzyW/e2XKx4E="
  docker_sets:
    - set: centos6-64
    - set: centos7-64
    - set: debian8-64
    - set: debian9-64
    - set: ubuntu1604-64
