name 'dhoppe-fail2ban'
version '0.1.0'

author 'Dennis Hoppe'
license 'GPLv2'
project_page 'http://github.com/dhoppe/puppet-fail2ban'
source 'git://github.com/dhoppe/puppet-fail2ban'
summary 'Fail2Ban Module'
description 'Fail2Ban Module for Debian, Ubuntu'
dependency 'puppetlabs/stdlib', '>=0.0.1'
